# 使用的语言
language: node_js

# 使用的nodejs版本
node_js:
 - v8.9.4

# 仓库的分支
branches:
  only:
  - master
install:

before_script:
 - npm install
 - npm install webpack -g
 - npm install webpack-dev-server -g